
commandes:
  - commande1:
      description: aaa
      execution: dir
  - commande2:
      description: bbbb
      execution: cmd /C test\run.bat
  - commande3:
      description: ccc
      execution: start test\run.bat

